// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.33.4
// source: internal/clipwire/clipwire.proto

package clipwire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadType int32

const (
	PayloadType_PAYLOAD_TYPE_UNSPECIFIED PayloadType = 0
	PayloadType_PAYLOAD_TYPE_TEXT        PayloadType = 1
	PayloadType_PAYLOAD_TYPE_URL         PayloadType = 2
	PayloadType_PAYLOAD_TYPE_IMAGE       PayloadType = 3
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0: "PAYLOAD_TYPE_UNSPECIFIED",
		1: "PAYLOAD_TYPE_TEXT",
		2: "PAYLOAD_TYPE_URL",
		3: "PAYLOAD_TYPE_IMAGE",
	}
	PayloadType_value = map[string]int32{
		"PAYLOAD_TYPE_UNSPECIFIED": 0,
		"PAYLOAD_TYPE_TEXT":        1,
		"PAYLOAD_TYPE_URL":         2,
		"PAYLOAD_TYPE_IMAGE":       3,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_clipwire_clipwire_proto_enumTypes[0].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_internal_clipwire_clipwire_proto_enumTypes[0]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_internal_clipwire_clipwire_proto_rawDescGZIP(), []int{0}
}

type ClipboardPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Type            PayloadType            `protobuf:"varint,2,opt,name=type,proto3,enum=clippy.clipwire.v1.PayloadType" json:"type,omitempty"`
	Sha256          []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	MimeType        string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes       uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClipboardPayload) Reset() {
	*x = ClipboardPayload{}
	mi := &file_internal_clipwire_clipwire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPayload) ProtoMessage() {}

func (x *ClipboardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipwire_clipwire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPayload.ProtoReflect.Descriptor instead.
func (*ClipboardPayload) Descriptor() ([]byte, []int) {
	return file_internal_clipwire_clipwire_proto_rawDescGZIP(), []int{0}
}

func (x *ClipboardPayload) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ClipboardPayload) GetType() PayloadType {
	if x != nil {
		return x.Type
	}
	return PayloadType_PAYLOAD_TYPE_UNSPECIFIED
}

func (x *ClipboardPayload) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ClipboardPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClipboardPayload) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ClipboardPayload) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type PayloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadChunk) Reset() {
	*x = PayloadChunk{}
	mi := &file_internal_clipwire_clipwire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadChunk) ProtoMessage() {}

func (x *PayloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipwire_clipwire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadChunk.ProtoReflect.Descriptor instead.
func (*PayloadChunk) Descriptor() ([]byte, []int) {
	return file_internal_clipwire_clipwire_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadChunk) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *PayloadChunk) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PayloadChunk) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *PayloadChunk) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *PayloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_clipwire_clipwire_proto protoreflect.FileDescriptor

var file_internal_clipwire_clipwire_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x70, 0x77,
	0x69, 0x72, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x63, 0x6c, 0x69, 0x70, 0x70, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x70, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xdb, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x70, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x6c, 0x69, 0x70, 0x70, 0x79, 0x2e, 0x63,
	0x6c, 0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x68,
	0x61, 0x32, 0x35, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x70, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x41, 0x59, 0x4c, 0x4f,
	0x41, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x52, 0x4c,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x03, 0x42, 0x23, 0x5a, 0x21, 0x63, 0x6c,
	0x69, 0x70, 0x70, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c,
	0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x3b, 0x63, 0x6c, 0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_clipwire_clipwire_proto_rawDescOnce sync.Once
	file_internal_clipwire_clipwire_proto_rawDescData []byte
)

func file_internal_clipwire_clipwire_proto_rawDescGZIP() []byte {
	file_internal_clipwire_clipwire_proto_rawDescOnce.Do(func() {
		file_internal_clipwire_clipwire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clipwire_clipwire_proto_rawDesc), len(file_internal_clipwire_clipwire_proto_rawDesc)))
	})
	return file_internal_clipwire_clipwire_proto_rawDescData
}

var file_internal_clipwire_clipwire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_clipwire_clipwire_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_clipwire_clipwire_proto_goTypes = []any{
	(PayloadType)(0),         // 0: clippy.clipwire.v1.PayloadType
	(*ClipboardPayload)(nil), // 1: clippy.clipwire.v1.ClipboardPayload
	(*PayloadChunk)(nil),     // 2: clippy.clipwire.v1.PayloadChunk
}
var file_internal_clipwire_clipwire_proto_depIdxs = []int32{
	0, // 0: clippy.clipwire.v1.ClipboardPayload.type:type_name -> clippy.clipwire.v1.PayloadType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_clipwire_clipwire_proto_init() }
func file_internal_clipwire_clipwire_proto_init() {
	if File_internal_clipwire_clipwire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clipwire_clipwire_proto_rawDesc), len(file_internal_clipwire_clipwire_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_clipwire_clipwire_proto_goTypes,
		DependencyIndexes: file_internal_clipwire_clipwire_proto_depIdxs,
		EnumInfos:         file_internal_clipwire_clipwire_proto_enumTypes,
		MessageInfos:      file_internal_clipwire_clipwire_proto_msgTypes,
	}.Build()
	File_internal_clipwire_clipwire_proto = out.File
	file_internal_clipwire_clipwire_proto_goTypes = nil
	file_internal_clipwire_clipwire_proto_depIdxs = nil
}
